### ISSUE TITLE
dd, yy,.. - does not work

### ISSUE THREAD

**Issue by v-sim** [Wansmer/langmapper.nvim#2]
dd (delete line), yy (copy  line),.. - (in translate) does not work after last update.

and prefix 'Langmapper: translate ...' for '--desc' — difficult to read.
maybe postfix is ​​better? or in conf?

**Comment by Wansmer** [comment]
`dd` and `yy` – it is built-ins nvim sequence. It should be work with `vim.opt.langmap` even without langmapper. (I tested it now – work for me with and without langmapper)

Show your langmapper config and value of `langmap`, I will see, why it could happen.

**Comment by v-sim** [comment]
> Show your langmapper config and value of `langmap`, I will see, why it could happen.
Sorry, i am using [LazyVim](https://github.com/LazyVim/LazyVim) and this has already happened with pure dd,yy,.. but now only with translated. Previous version (with specials_keys,..) work fine.
Thanks anyway, I'll look into solutions.

**Comment by Wansmer** [comment]
> ps: my workaround:
> 
> ```lua
>       local map = require("langmapper").map
>       map("n", "dd", "dd")
>       map("n", "yy", "yy")
> ```

I understand, what is happens.

You should add options `{ remap = true }` or best way, remove these mappings, remove `local map = require("langmapper").map` and try new feature `require('langmapper').automapping()` at the end of your `init.lua`. See README for more info. It is big update for more automation.

**Comment by v-sim** [comment]
> remap = true
> require('langmapper').automapping()

Does not help.
In my case there are many points of failure - [lazyvim](https://github.com/LazyVim/LazyVim) include [noice](https://github.com/folke/noice.nvim), [mini.ai](https://github.com/echasnovski/mini.ai), [which-key](https://github.com/folke/which-key.nvim),..
folding, ["text objects"](https://www.baeldung.com/linux/text-objects-in-vim#bd-text-object-operation-grammar) also don't work. In my case only working:
```lua
      local map = require("langmapper").map
      map("n", "dd", "dd")
      map("n", "yy", "yy")
      map("n", "zo", "zo")
      map("n", "zc", "zc")
      map("n", "zf", "zf")
      map("n", "ci", "ci")
      map("n", "di", "di")
      map("n", "vi", "vi")
      map("n", "yi", "yi")
      …
```
ps:
Your new architecture is definitely better (but not for me yet).
Of course, I will continue to try options (without downgrade to previous version) and if I find a solution, I will write here.
Thanks for the quick response.

**Comment by v-sim** [comment]
only when i set `hack_keymap = false,`  work like a charm.
thanks.

**Comment by Wansmer** [comment]
@v-sim, I did an example, how to use Langmapper + LazyNvim with `hack_keymap = true`: https://github.com/Wansmer/LazyWithLangmapper

If still relevant, checks `init.lua`, `config/options.lua`, `plugings/which-key.lua` and `plugins/langmapper.lua`. It is a temporary solution, but maximum of your use cases works.
