### ISSUE TITLE
V-Line, V-Block selections don't work in keyboard layouts except English

### ISSUE THREAD

**Issue by Nikita0x** [Wansmer/langmapper.nvim#36]
### The problem:
Visual selections in modes `V-LINE` and `V-BLOCK` - don't work in other layouts but do work in English.

I have my default config for langmapper, and don't have any other keybinds for Ukrainian or Russian languages that could interfere with that functionality.

But arrows (UP/DOWN) - work in other layouts

```lua
return {
	"Wansmer/langmapper.nvim",
	lazy = false,
	priority = 1,
	config = function()
		require("langmapper").setup({
		})
	end,
}
```

https://github.com/user-attachments/assets/9f7164c7-8873-47de-ab2e-cfa369272f93

**Comment by Wansmer** [comment]
Make sure that `vim.opt.langmap` is set. `langmapper` handles mappings, `vim.opt.langmap` handles movements and other commands.

**Comment by Nikita0x** [comment]
> Make sure that `vim.opt.langmap` is set. `langmapper` handles mappings, `vim.opt.langmap` handles movements and other commands.

Thank you, this fixed it!
