### ISSUE TITLE
[Feature Request] Allow new keymaps to be ignored by whichkey

### ISSUE THREAD

**Issue by ventsislav-georgiev** [Wansmer/langmapper.nvim#37]
Small feature request to allow forcing all keymap descriptions to `which_key_ignore`.
This is for hiding all langmapper registered keys from [whichkey](https://github.com/folke/which-key.nvim/blob/8badb359f7ab8711e2575ef75dfe6fbbd87e4821/lua/which-key/mappings.lua#L243). 

I've tested using `hack_keymap = false` and just modifying the auto.lua to just set desc to `which_key_ignore` and seems to work. Will be great to have it as an option.

[Side question] What is the difference between:
`hack_keymap = true` with `automapping({ buffer = false })`
vs
`hack_keymap = false` with `automapping({ buffer = true })`

**Comment by Wansmer** [comment]
I'll consider adding an option to add custom desc for keymaps. While you can filter mappings for which-key by 'LM (' prefix.

> What is the difference between

These settings are used for different plugin use cases, more details in the readme: https://github.com/Wansmer/langmapper.nvim?tab=readme-ov-file#usage

**Comment by Wansmer** [comment]
With #38  you can use the `custom_desc` method to set your own description for each translated mapping.

**Comment by ventsislav-georgiev** [comment]
Works perfectly! Thanks.
