### ISSUE TITLE
Keybindings with Alt don't work

### ISSUE THREAD

**Issue by RobberFox** [Wansmer/langmapper.nvim#40]
For example, I open the file tree with `<A-h>`:
```lua
vim.keymap.set({"n", "i"}, "<A-h>", "<cmd>Neotree toggle=true<CR>" )
```
In russian that hotkey doesn't work. 
### Things I've tried
1. Editing the langmapper config:
```lua
...
    map_all_ctrl = true,
    map_all_alt = true,
...
```
2. Changing `<A-h>` to meta key: `<M-h>`

But none of those work.

**Comment by RobberFox** [comment]
I just checked, it's a problem only with fcitx5, on KDE with its default input method switcher it's working properly. I just don't get why it's only Alt and not Ctrl either.

**Comment by Wansmer** [comment]
> I just found out it's a problem only with fcitx5 (I'm using Awesome Window Manager). I checked it on KDE with its default input method switcher and it's working properly. 

So, it is not a langmapper issue.

> I just don't get why it's only Alt and not Ctrl either.

You may need to change the escape key codes on terminal layers

**Comment by RobberFox** [comment]
I'm also using Kitty, is this the right place to check for escape codes behaviour? https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by Wansmer** [comment]
> I'm also using Kitty, is this the right place to check for escape codes behaviour? https://sw.kovidgoyal.net/kitty/keyboard-protocol/

Looks like yes

**Comment by RobberFox** [comment]
In the end I just ditched fcitx5 and now trying to use setxkbmap. It works the same as on KDE, so pretty well.
The only thing is that with the keybinding (`vim.keymap.set({"n", "i"}, "<A-h>", "<cmd>Neotree toggle=true<CR>" )`), if I'm in insert mode, I have to press Alt+h twice instead of once.

**Comment by RobberFox** [comment]
> The only thing is that with the keybinding (vim.keymap.set({"n", "i"}, "<A-h>", "<cmd>Neotree toggle=true<CR>" )), if I'm in insert mode, I have to press Alt+h twice instead of once.

Using the `local map = require("langmapper").map` now everything is fine since I assign both `<A-h>` and russian `<A-р>`
